"""add is_public and play_count

Revision ID: 659f128c2856
Revises: 6e64ba2229a2
Create Date: 2026-08-27 12:51:05.379280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '659f128c2856'
down_revision: Union[str, Sequence[str], None] = '6e64ba2229a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('songs', sa.Column('play_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'play_count')
    op.drop_column('songs', 'is_public')
    # ### end Alembic commands ###
