export enum OrderStatus {
  INITIATED = 'INITIATED',
  AUTHORIZED = 'AUTHORIZED',
  PENDING_DEPOSIT = 'PENDING_DEPOSIT',
  PAID = 'PAID',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  EXPIRED = 'EXPIRED'
}

export enum PaymentStatus {
  INITIATED = 'INITIATED',
  AUTHORIZED = 'AUTHORIZED',
  PENDING_DEPOSIT = 'PENDING_DEPOSIT',
  PAID = 'PAID',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  EXPIRED = 'EXPIRED'
}

export enum DocumentIssueStatus {
  READY = 'READY',
  PROCESSING = 'PROCESSING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}

export enum CashReceiptStatus {
  READY = 'READY',
  PROCESSING = 'PROCESSING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}

export enum DispatchStatus {
  READY = 'READY',
  PROCESSING = 'PROCESSING',
  SENT = 'SENT',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED'
}

export enum RefundStatus {
  REQUESTED = 'REQUESTED',
  PROCESSING = 'PROCESSING',
  DONE = 'DONE',
  FAILED = 'FAILED'
}

export enum ReceiptType {
  NONE = 'NONE',
  TAX_INVOICE = 'TAX_INVOICE',
  INVOICE = 'INVOICE',
  CASH_RECEIPT = 'CASH_RECEIPT',
  PERSONAL_RECEIPT = 'PERSONAL_RECEIPT'
}

export enum CashReceiptType {
  INCOME_DEDUCTION = 'INCOME_DEDUCTION',
  EXPENSE_PROOF = 'EXPENSE_PROOF'
}

export enum CashReceiptIdentityType {
  PHONE = 'PHONE',
  PERSONAL_ID = 'PERSONAL_ID',
  BUSINESS_REG_NO = 'BUSINESS_REG_NO'
}

export enum InvoiceType {
  TAX_INVOICE = 'TAX_INVOICE',
  INVOICE = 'INVOICE'
}

export enum AdminRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  OPS_ADMIN = 'OPS_ADMIN',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
  DEVELOPER = 'DEVELOPER',
  READONLY = 'READONLY'
}

export enum PaymentMethod {
  CREDIT_CARD = 'CREDIT_CARD',
  KAKAO_PAY = 'KAKAO_PAY',
  NAVER_PAY = 'NAVER_PAY',
  PAYCO = 'PAYCO',
  TOSS_PAY = 'TOSS_PAY',
  ACCOUNT_TRANSFER = 'ACCOUNT_TRANSFER',
  VIRTUAL_ACCOUNT = 'VIRTUAL_ACCOUNT',
  MOBILE_PHONE = 'MOBILE_PHONE',
  ETC_SIMPLE_PAY = 'ETC_SIMPLE_PAY'
}

export enum ReconciliationStatus {
  UNRECONCILED = 'UNRECONCILED',
  AUTO_MATCHED = 'AUTO_MATCHED',
  MANUALLY_ADJUSTED = 'MANUALLY_ADJUSTED',
  DISCREPANCY_FLAGGED = 'DISCREPANCY_FLAGGED'
}

export enum TraceStage {
  PG_PAYMENT = 'PG_PAYMENT',
  CREDIT_DISPATCH = 'CREDIT_DISPATCH',
  TAX_DOCUMENT = 'TAX_DOCUMENT',
  CASH_RECEIPT = 'CASH_RECEIPT',
  CHINA_WEBHOOK = 'CHINA_WEBHOOK'
}

export enum TraceStatus {
  INITIATED = 'INITIATED',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  RETRYING = 'RETRYING'
}
