"""baseline_all_tables

Revision ID: c2fbb2654cf3
Revises: 
Create Date: 2026-05-26 13:51:02.522798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2fbb2654cf3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salvation_journey',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscriber_id', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=False),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('trigger_signal', sa.String(length=20), nullable=False),
    sa.Column('trigger_quote', sa.Text(), nullable=True),
    sa.Column('interaction_id', sa.String(length=40), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.interaction_id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscriber.subscriber_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salvation_journey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salvation_journey_subscriber_id'), ['subscriber_id'], unique=False)

    with op.batch_alter_table('document_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_audience', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('target_stage', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('emotion_tone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('length_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_salvation_stage', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('darakbang_tier', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('salvation_focus_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('gospel_core_tag', sa.Boolean(), nullable=False))

    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interaction_trace_id'), ['trace_id'], unique=False)

    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faith_stage', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('emotional_state', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('age_group', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('current_struggle', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preferred_tone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('consent_data', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('consent_kakao', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('session_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_questions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_emotion', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('onboarding_step', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_darakbang_member', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_believer', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('salvation_status', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('salvation_confidence', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('salvation_last_signal_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assume_saved', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('darakbang_role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('darakbang_chapter', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('darakbang_joined_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('darakbang_verified', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.drop_column('darakbang_verified')
        batch_op.drop_column('darakbang_joined_at')
        batch_op.drop_column('darakbang_chapter')
        batch_op.drop_column('darakbang_role')
        batch_op.drop_column('assume_saved')
        batch_op.drop_column('salvation_last_signal_at')
        batch_op.drop_column('salvation_confidence')
        batch_op.drop_column('salvation_status')
        batch_op.drop_column('is_believer')
        batch_op.drop_column('is_darakbang_member')
        batch_op.drop_column('onboarding_step')
        batch_op.drop_column('last_emotion')
        batch_op.drop_column('total_questions')
        batch_op.drop_column('session_count')
        batch_op.drop_column('consent_kakao')
        batch_op.drop_column('consent_data')
        batch_op.drop_column('preferred_tone')
        batch_op.drop_column('current_struggle')
        batch_op.drop_column('gender')
        batch_op.drop_column('age_group')
        batch_op.drop_column('emotional_state')
        batch_op.drop_column('faith_stage')

    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interaction_trace_id'))

    with op.batch_alter_table('document_version', schema=None) as batch_op:
        batch_op.drop_column('gospel_core_tag')
        batch_op.drop_column('salvation_focus_score')
        batch_op.drop_column('darakbang_tier')
        batch_op.drop_column('target_salvation_stage')
        batch_op.drop_column('length_minutes')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('emotion_tone')
        batch_op.drop_column('target_stage')
        batch_op.drop_column('target_audience')

    with op.batch_alter_table('salvation_journey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salvation_journey_subscriber_id'))

    op.drop_table('salvation_journey')
    # ### end Alembic commands ###
